apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql-root-password: cHJlUHJvZHVjdGlvblJvb3RQYXNzd29yZAo= #preProductionRootPassword
  mysql-user: ZGF0YS1yb3lhbGUtcHJlLXVzZXIK #data-royale-pre-user
  mysql-password: cHJlUHJvZHVjdGlvblBhc3N3b3JkCg== #preProductionPassword
